export const selectIsLoading = state => state.cars.isLoading;
export const selectIsError = state => state.cars.isError;
export const selectBrands = state => state.cars.brands;
export const selectCars = state => state.cars.cars;
export const selectTotalCars = state => state.cars.totalCars;
export const selectPage = state => state.cars.page;
export const selectTotalPages = state => state.cars.totalPages;
export const selectCar = state => state.cars.car;
export const selectFilter = state => state.cars.filters;
